version: "3"
services:
  TestNGWeb:
    image: darkklin/finalproject
    container_name: TestNGWeb
    environment:
      - HUB_HOST=192.168.56.1
      - MODULE=TestNGWeb.xml
    volumes:
      - /c/home/qa/jenkins/workspace/Automtion-Project-run-tests/allure-results:/usr/share/selenium-docker/allure-results
  TestNGApi:
    image: darkklin/finalproject
    container_name: TestNGApi
    environment:
      - HUB_HOST=192.168.56.1
      - MODULE=TestNGApi.xml
    volumes:
      - /c/home/qa/jenkins/workspace/Automtion-Project-run-tests/allure-results:/usr/share/selenium-docker/allure-results
